package io.github.gill.rahul.financemanager.ui.screen.settings

import io.github.gill.rahul.financemanager.R


object IconsMap {
    val collection = mapOf(
        "entertainment" to mapOf(
            "swimming" to R.drawable.swimming,
            "skull" to R.drawable.skull,
            "brand_netflix" to R.drawable.brand_netflix,
            "device_speaker" to R.drawable.device_speaker,
            "ball_football" to R.drawable.ball_football,
            "disc" to R.drawable.disc,
            "music" to R.drawable.music,
            "brand_youtube_filled" to R.drawable.brand_youtube_filled,
            "pumpkin_scary" to R.drawable.pumpkin_scary,
            "device_gamepad_2" to R.drawable.device_gamepad_2,
            "brand_amazon" to R.drawable.brand_amazon,
            "air_balloon" to R.drawable.air_balloon,
            "ball_american_football" to R.drawable.ball_american_football,
            "beach" to R.drawable.beach,
            "ping_pong" to R.drawable.ping_pong,
            "ball_basketball" to R.drawable.ball_basketball,
        ),
        "general" to mapOf(
            "category_2" to R.drawable.category_2,
            "confetti" to R.drawable.confetti,
            "shield_lock_filled" to R.drawable.shield_lock_filled,
            "balloon" to R.drawable.balloon,
            "books" to R.drawable.books,
        ),
        "shopping" to mapOf(
            "shoe" to R.drawable.shoe,
            "shirt_sport" to R.drawable.shirt_sport,
            "shopping_cart" to R.drawable.shopping_cart,
            "shopping_bag" to R.drawable.shopping_bag,
            "device_mobile" to R.drawable.device_mobile,
            "armchair_2" to R.drawable.armchair_2,
            "device_desktop" to R.drawable.device_desktop,
        ),
        "travel" to mapOf(
            "motorbike" to R.drawable.motorbike,
            "trekking" to R.drawable.trekking,
            "bus" to R.drawable.bus,
            "plane" to R.drawable.plane,
            "speedboat" to R.drawable.speedboat,
            "gas_station" to R.drawable.gas_station,
            "train" to R.drawable.train,
            "backpack" to R.drawable.backpack,
        ),
        "peoplePets" to mapOf(
            "friends" to R.drawable.friends,
            "fish" to R.drawable.fish,
            "paw_filled" to R.drawable.paw_filled,
            "dog" to R.drawable.dog,
            "cat" to R.drawable.cat,
        ),
        "finance" to mapOf(
            "brand_mastercard" to R.drawable.brand_mastercard,
            "credit_card_filled" to R.drawable.credit_card_filled,
            "brand_cashapp" to R.drawable.brand_cashapp,
            "wallet" to R.drawable.wallet,
            "building_bank" to R.drawable.building_bank,
            "currency_pound" to R.drawable.currency_pound,
            "brand_stripe" to R.drawable.brand_stripe,
            "gift_card_filled" to R.drawable.gift_card_filled,
            "home_dollar" to R.drawable.home_dollar,
            "currency_dollar" to R.drawable.currency_dollar,
            "pig_money" to R.drawable.pig_money,
            "graph" to R.drawable.graph,
            "chart_bar" to R.drawable.chart,
            "currency_euro" to R.drawable.currency_euro,
            "timeline" to R.drawable.timeline,
        ),
        "food" to mapOf(
            "pizza" to R.drawable.pizza,
            "cup" to R.drawable.cup,
            "ice_cream" to R.drawable.ice_cream,
            "meat" to R.drawable.meat,
            "beer" to R.drawable.beer,
            "coffee" to R.drawable.coffee,
            "soup" to R.drawable.soup,
            "glass" to R.drawable.glass,
            "cheese" to R.drawable.cheese,
            "sausage" to R.drawable.sausage,
            "candy" to R.drawable.candy,
            "ice_cream_2" to R.drawable.ice_cream_2,
        ),
        "medical" to mapOf(
            "vaccine" to R.drawable.vaccine,
            "wheelchair" to R.drawable.wheelchair,
            "first_aid_kit" to R.drawable.first_aid_kit,
            "heartbeat" to R.drawable.heartbeat,
        )
    )
}
